services:
  teabot:
    build: .
    container_name: teabot
    volumes:
      - ./data:/data
    entrypoint: ["python", "bot.py"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: unless-stopped
