services:
  teabot:
    image: teabot_image:1.1
    container_name: teabot
    volumes:
      - ./data:/data
    entrypoint: ["python", "bot.py"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3G
    restart: unless-stopped
